export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USERS_DATA = 'SET_USERS_DATA';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const SET_BOOKMARKED_USERS = 'SET_BOOKMARKED_USERS';
